docs(examples): Live strategy for several tickers. Strategy prints OHLCV for every completed candle.
Tinkoff/invest-python pull request #205
Opened 2023-03-13 12:03 UTC by WISEPLAT

Привет всем!
Хотелось бы добавить в примеры:

Пример live стратегии для нескольких тикеров. Вывод OHLCV для каждой сформировавшейся свечи.

Прошу рассмотреть и подтвердить.
Спасибо!

2023-03-13 13:24 UTC, WISEPLAT commented
Всё пофиксил )) прошу заапрувить)

> Привет всем! Хотелось бы добавить в примеры:
> 
> Пример live стратегии для нескольких тикеров. Вывод OHLCV для каждой сформировавшейся свечи.
> 
> Прошу рассмотреть и подтвердить. Спасибо!

2023-03-20 17:30 UTC, irusland requested changes
CI падает, надо разобраться почему и пофиксить

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
Долгое время не понимал что такое `wiseplat` потом осознал, что это ник. Возможно в названии файла не стоит его добавлять. Либо делать папку `examples/contrib/wiseplat/` и туда добавлять свои экзамплы.

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    """PrintOnlyCandles strategy."""
Такая докстринга не несёт полезной нагрузки и при смене названия класса сразу же потеряет свою актуальность. Её либо стоит убрать, либо дополнить описание стратегии.

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    )  # ..._1_MIN,..._5_MIN, ..._15_MIN, ..._HOUR, ..._DAY
Комменты излишни, IDE сама подскажет какие поля есть у `CandleInterval`

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    portfolio = {"BBG004730N88", "BBG004730ZJ9"}  # SBER, VTBR
```suggestion
    sber_figi = "BBG004730N88"
    vtbr_figi = "BBG004730ZJ9"
    portfolio = {sber_figi, vtbr_figi}
```

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
```suggestion
    with AsyncClient(token=TOKEN) as client:
```

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +class PrintOnlyCandlesStrategy:
```suggestion
class LogOnlyCandlesStrategy:
```

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    days_back = 1
В итоге по коду идёт использование `timedelta(days=self.days_back)`

Лучше назвать параметр по типу from_delta (но тут под вопросом как лучше назвать) и уже использовать timedelta, а не внутри кастовать

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    check_interval = 10  # seconds to check interval for new completed candle
```suggestion
    check_interval_period = timedelta(seconds=10)  # period between checking interval for new completed candle
```

а далее `check_interval_period.total_seconds()`

2023-03-20 17:30 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +                if candle.is_complete:  # if candle is complete
```suggestion
                if candle.is_complete: 
```

2023-03-20 17:58 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +class PrintOnlyCandlesStrategy:
ok

2023-03-20 18:00 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    """PrintOnlyCandles strategy."""
ok, поправлю

2023-03-20 18:01 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +                if candle.is_complete:  # if candle is complete
ок

2023-03-20 18:13 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    check_interval = 10  # seconds to check interval for new completed candle
ok

2023-03-20 18:13 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    check_interval = 10  # seconds to check interval for new completed candle
зачем усложнять?

2023-03-20 18:14 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    days_back = 1
не нужно усложнять

2023-03-20 18:14 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    )  # ..._1_MIN,..._5_MIN, ..._15_MIN, ..._HOUR, ..._DAY
ок

2023-03-20 18:30 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
так не сработает.

2023-03-20 18:49 UTC, WISEPLAT commented
Поправил. Прошу заапрувить.

2023-03-20 18:49 UTC, WISEPLAT commented
> CI падает, надо разобраться почему и пофиксить

Поправил. Прошу заапрувить.

2023-03-21 06:55 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
Ага, я немного ошибся, надо async добавить https://github.com/Tinkoff/invest-python/blob/main/examples/async_client.py

2023-03-21 06:57 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    check_interval = 10  # seconds to check interval for new completed candle
Усложнять не надо, как по мне, оно читабельнее будет, и комменты можно будет убрать)

2023-03-21 06:57 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    check_interval = 10  # seconds to check interval for new completed candle
Ну либо _seconds добавить в название переменной check_interval, неочевидно

2023-03-21 07:11 UTC, irusland commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +                # put your strategy code here for live
А будет удобно эту стратегию сделать в соответствии с интерфейсом? https://github.com/Tinkoff/invest-python/blob/618864e71a5ff91b422927a2fe594eb7d40b6b8d/tinkoff/invest/strategies/base/strategy_interface.py#L7

Возможно ли будет сделать стратегию по типу moving average? https://github.com/Tinkoff/invest-python/tree/618864e71a5ff91b422927a2fe594eb7d40b6b8d/tinkoff/invest/strategies/moving_average

2023-03-21 07:11 UTC, irusland commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +            if candle not in self.candles:
Сейчас понял, что это рано или поздно будет все медленнее и медленнее работать

2023-03-21 07:12 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
Может issue завести на эту доработку? Или не понравилось моё предложение?

2023-03-21 07:29 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +            if candle not in self.candles:
это да, это же пример - нет цели создать идеальную модель бесплатно...

2023-03-21 07:31 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +                # put your strategy code here for live
предлагаю это заапрувить - потом сделать версию 2.0 - улучшенную)))

2023-03-21 07:32 UTC, WISEPLAT commented
предлагаю это заапрувить - потом сделать версию 2.0 - улучшенную))) с доп оптимизацией.

2023-03-21 07:36 UTC, irusland commented
> предлагаю это заапрувить - потом сделать версию 2.0 - улучшенную))) с доп оптимизацией.

Предлагаю сразу доводить до ума, чтобы тех долга не копилось. 

Комменты сверху все же надо порешать.

2023-03-21 07:37 UTC, WISEPLAT commented
> > предлагаю это заапрувить - потом сделать версию 2.0 - улучшенную))) с доп оптимизацией.
> 
> Предлагаю сразу доводить до ума, чтобы тех долга не копилось.
> 
> Комменты сверху все же надо порешать.

как это вернуть?

return AsyncServices(
            channel,
            token=self._token,
            sandbox_token=self._sandbox_token,
            app_name=self._app_name,
        )

2023-03-21 07:39 UTC, WISEPLAT commented
> 

какие принципиальные не решены? Чтобы понимать. - а то здесь уже путаешься в кол-ве ...

2023-03-21 07:39 UTC, irusland commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
```python
return client
```
?

2023-03-21 07:40 UTC, irusland commented
> какие принципиальные не решены? Чтобы понимать. - а то здесь уже путаешься в кол-ве ...

Те, которые не пофикшены

2023-03-21 07:41 UTC, WISEPLAT commented
> 

так я все исправил

2023-03-21 07:42 UTC, irusland commented
Давайте хотя бы добьём AsyncClient

2023-03-21 07:43 UTC, WISEPLAT commented
> Давайте хотя бы добьём AsyncClient

можно, какое предложение? если нет возвращаемого объекта:
 return AsyncServices(
            channel,
            token=self._token,
            sandbox_token=self._sandbox_token,
            app_name=self._app_name,
        )

от     async def __aenter__(self) -> AsyncServices:

2023-03-21 07:46 UTC, WISEPLAT commented
раз по другому не получается вернуть такой объект - посмотрел в исходниках, то может пример всё же заапрувим - ведь это позволит народу сэкономить кучу времени на создание прототипа структуры своей стратегии используя API Тинькофф

2023-03-21 16:07 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
такое ощущение что вам не особо хочется чтобы люди получили рабочий пример со структурой для своей стратегии. это не влияет ни на что, просто например мне приятно - и вам за понимание этого Спасибо)))

2023-03-21 16:08 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_OHLCV.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
это не работает, может всё таки текущую реализацию заапрувим? ведь она нормально работает - и дает великолепную возможность делать больше стратегий для API Тинькофф.

2023-03-23 08:45 UTC, WISEPLAT commented
> Апрувим?



> Давайте хотя бы добьём AsyncClient

Добрый день!
Т.к. по другому не получается вернуть такой объект - посмотрел в исходниках, то может пример всё же заапрувим? 
- Ведь это позволит народу сэкономить кучу времени на создание прототипа структуры своей стратегии используя API Тинькофф и больше клиентов станут использовать торговлю через Тинькофф.
Прошу заапрувить пример. Спасибо!

2023-03-23 20:13 UTC, irusland commented
> по другому не получается вернуть такой объект 

какой объект вам необходимо вернуть?

2023-03-24 04:24 UTC, WISEPLAT commented
> нет возвращаемого объекта: return AsyncServices( channel, token=self._token, sandbox_token=self._sandbox_token, app_name=self._app_name, )
> 
> от async def **aenter**(self) -> AsyncServices:

нет возвращаемого объекта:
return AsyncServices(
channel,
token=self._token,
sandbox_token=self._sandbox_token,
app_name=self._app_name,
)

от async def aenter(self) -> AsyncServices:

2023-03-24 05:07 UTC, irusland commented
К сожалению я не смог понять что значит `нет возвращаемого объекта` поэтому подготовил фикс который просил вас сделать.
Примените его
[fix(review)__use_propper_async_with.patch](https://github.com/Tinkoff/invest-python/files/11058575/fix.review.__use_propper_async_with.patch)

2023-03-24 06:52 UTC, WISEPLAT commented
> > по другому не получается вернуть такой объект
> 
> какой объект вам необходимо вернуть?



> К сожалению я не смог понять что значит `нет возвращаемого объекта` поэтому подготовил фикс который просил вас сделать. Примените его [fix(review)__use_propper_async_with.patch](https://github.com/Tinkoff/invest-python/files/11058575/fix.review.__use_propper_async_with.patch)

Готово

2023-03-24 07:07 UTC, WISEPLAT commented
> К сожалению я не смог понять что значит `нет возвращаемого объекта` поэтому подготовил фикс который просил вас сделать. Примените его [fix(review)__use_propper_async_with.patch](https://github.com/Tinkoff/invest-python/files/11058575/fix.review.__use_propper_async_with.patch)

Готово. Протестил - всё работает.

2023-03-27 06:02 UTC, irusland commented
Поддержите мастер пожалуйста, чтобы тесты прошли.

2023-03-27 10:16 UTC, WISEPLAT commented
> Поддержите мастер пожалуйста, чтобы тесты прошли.

Добрый день! Готово.

2023-03-27 20:14 UTC, irusland approved these changes

2023-03-28 05:01 UTC, WISEPLAT commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
> Надо переделать эту часть на красивый контекстный менеджер

Так уже же сделали ... в закладке "Files changed" видно что теперь там так:
`async def run_strategy(portfolio, timeframe, days_back, check_interval):
    """From this function we are starting
    strategy for every ticker from portfolio.
    """
    async with AsyncClient(token=TOKEN, app_name="TinkoffApp") as client:
        strategy_tasks = []
        for instrument in portfolio:`

https://postimg.cc/SJBqQ5Xm

2023-03-28 05:11 UTC, irusland commented on examples/wiseplat_live_strategy_print_ohlcv.py
> +    client = await AsyncClient(token=TOKEN, app_name="TinkoffApp").__aenter__()
Старый коммент всплыл сюда почему-то

2023-03-28 05:17 UTC, WISEPLAT commented
Can you please merge this pull request? 
P.S. It is approved by @irusland

2023-03-28 05:18 UTC, merged